delete from AUTH_ATTR_ACTION WHERE ATTRIBUTE_ID IN (45,46,47,48,49,50,51,52,53);
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (46, '/admin/weeklyReport/weeklyReportFill.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (46, '/admin/weeklyReport/weeklyReportFillProjectQuery.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (46, '/admin/weeklyReport/weeklyReportList.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (46, '/admin/weeklyReport/weeklyReportListGistProject.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (47, '/admin/weeklyReport/weeklyReportAdd.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (47, '/admin/weeklyReport/insertWeeklyReportSave.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (47, '/admin/weeklyReport/insertWeeklyReportSubmit.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (48, '/admin/weeklyReport/weeklyReportUpdate.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (48, '/admin/weeklyReport/updateWeeklyReportSave.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (48, '/admin/weeklyReport/updateWeeklyReportSubmit.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (49, '/admin/weeklyReport/weeklyReportApprove.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (49, '/admin/weeklyReport/weeklyReportUnapprovedList.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (49, '/admin/weeklyReport/projectListByApprovalTime.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (50, '/admin/weeklyReport/weeklyReportApproveFill.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (50, '/admin/weeklyReport/insertRptWeeklyApprove.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (51, '/admin/weeklyReport/weeklyReportListApproved.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (51, '/admin/weeklyReport/weeklyReportListApprovedByPkProj.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (52, '/admin/task/binningTask.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (53, '/admin/task/forcibleExecutionTask.ajax', '1');


INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, CREATE_TIME, VERIFY_RESOURCE) VALUES (45, '/admin/project/projectDetails.do',  '2017-05-05 00:00:00', '1');