delete from AUTH_ATTRIBUTE ;
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (21, 'ResourceManageQuery', 'ResourceManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (39, 'WorkLoadManageQuery', 'WorkLoadManage', '查询', '#', 2, 1, null, null, null);


INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (1, 'UserManageQuery', 'UserManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (2, 'UserManageAdd', 'UserManage', '新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (3, 'UserManageModi', 'UserManage', '修改', '#', 2, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (4, 'UserManageInVal', 'UserManage', '归档', '#', 2, 4, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (40, 'UserManageDel', 'UserManage', '删除', '#', 2, 5, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (41, 'UserManageDetail', 'UserManage', '查看详情', '#', 2, 6, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (42, 'UserManageRecovery', 'UserManage', '恢复', '#', 2, 7, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (43, 'UserManageImport', 'UserManage', '导入', '#', 2, 8, null, null, null);


INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (5, 'DeptManageQuery', 'DeptManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (6, 'DeptManageAdd', 'DeptManage', '新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (7, 'DeptManageModi', 'DeptManage', '修改', '#', 2, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (8, 'DeptManageDel', 'DeptManage', '删除', '#', 2, 4, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (9, 'RoleManageQuery', 'RoleManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (10, 'RoleManageAdd', 'RoleManage', '新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (11, 'RoleManageModi', 'RoleManage', '修改', '#', 2, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (12, 'RoleManageInVal', 'RoleManage', '删除', '#', 2, 4, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (14, 'CreateProjQuery', 'CreateProj', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (15, 'CreateProjAdd', 'CreateProj', '新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (16, 'CreateProjModi', 'CreateProj', '修改', '#', 2, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (17, 'CreateProjDel', 'CreateProj', '删除', '#', 2, 4, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (45, 'CreateProjDetail', 'CreateProj', '详情', '#', 2, 5, null, null, null);

INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (18, 'ChangeProjQuery', 'ChangeProj', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (19, 'ChangeProjChange', 'ChangeProj', '变更', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (20, 'ChangeProjDetail', 'ChangeProj', '变更详情', '#', 1, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (57, 'QueryProjDetail', 'QueryProj', '项目详情', '#', 1, 1);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (22, 'ResourceManageAllocate', 'ResourceManage', '资源分配', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (23, 'TaskManageQuery', 'TaskManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (24, 'TaskManageAdd', 'TaskManage', '新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (25, 'TaskManageModi', 'TaskManage', '修改', '#', 2, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (26, 'TaskManageInVal', 'TaskManage', '封存', '#', 2, 4, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (27, 'TaskManageDel', 'TaskManage', '删除', '#', 2, 5, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (28, 'TaskManageExport', 'TaskManage', '导入', '#', 2, 6, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (29, 'TaskManageAllocate', 'TaskManage', '任务分配', '#', 2, 7, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (30, 'ProgressManageQuery', 'ProgressManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (31, 'ProgressManageQueryDetail', 'ProgressManage', '查询进度详情', '#', 1, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (32, 'FIllLogManageQuery', 'FIllLogManage', '日志查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (33, 'FIllLogManageAdd', 'FIllLogManage', '日志新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (34, 'FIllLogManageExport', 'FIllLogManage', '日志导出', '#', 1, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (35, 'DictManageQuery', 'DictManage', '查询', '#', 1, 1, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (36, 'DictManageAdd', 'DictManage', '新增', '#', 2, 2, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (37, 'DictManageModi', 'DictManage', '修改', '#', 2, 3, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (38, 'DictManageInVal', 'DictManage', '封存', '#', 2, 4, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (44, 'DictManageRecovery', 'DictManage', '解封', '#', 2, 5, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (13, 'RoleUserManage', 'RoleManage', '人员列表', '#', 2, 5, null, null, null);


INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (46, 'RptReportFill', 'RptWeeklyFillManage', '查询', '#', 1, 1);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (47, 'RptReportAdd', 'RptWeeklyFillManage', '周报填写', '#', 2, 2);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (48, 'RptReportUpdate', 'RptWeeklyFillManage', '周报修改', '#', 2, 3);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (49, 'RptWeeklyApprove', 'RptWeeklyApprManage', '查询', '#', 1, 1);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (50, 'RptWeeklyApproveAdd', 'RptWeeklyApprManage', '审批', '#', 2, 2);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (51, 'RptWeeklyApproved', 'RptWeeklyApprManage', '历史周报', '#', 2, 3);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (52, 'TaskManageDevan', 'TaskManage', '解封', '#', 2, 8);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (53, 'TaskManageForce', 'TaskManage', '强制完成', '#', 2, 9);


INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (54, 'avoidLandingCache', 'WorkLogViewManage', '日志查看', '#', 1, 1);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (55, 'WorkLogViewExport', 'WorkLogViewManage', '日志导出', '#', 2, 2);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (56, 'workLogViewVisual', 'WorkLogViewManage', '日志可视化', '#', 2, 3);
