delete from ROLE_DATA_TYPE ;
INSERT INTO ROLE_DATA_TYPE (DATA_ID, DATA_NAME, DATA_DESC, DATA_CODE) VALUES (1, '全公司', '全公司', '01');
INSERT INTO ROLE_DATA_TYPE (DATA_ID, DATA_NAME, DATA_DESC, DATA_CODE) VALUES (2, '所在部门', '所在部门', '02');
INSERT INTO ROLE_DATA_TYPE (DATA_ID, DATA_NAME, DATA_DESC, DATA_CODE) VALUES (3, '项目经理', '项目经理', '03');
INSERT INTO ROLE_DATA_TYPE (DATA_ID, DATA_NAME, DATA_DESC, DATA_CODE) VALUES (4, '所在项目', '所在项目', '04');
