delete from AUTH_ATTRIBUTE WHERE ATTRIBUTE_CODE IN ('QueryProjDetail');
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (57, 'QueryProjDetail', 'QueryProj', 'ÏîÄ¿ÏêÇé', '#', 1, 1);
