delete from AUTH_ATTR_ACTION WHERE ATTRIBUTE_ID IN (57);
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (57, '/admin/projectQuery/project.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (57, '/admin/projectQuery/projectQuery.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (57, '/admin/projectQuery/dirTree.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (57, '/admin/projectQuery/projectDetails.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (57, '/admin/projectQuery/contrast.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (57, '/admin/projectQuery/projectDetails.ajax', '1');