INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (40, '/admin/user/userDelete.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (41, '/admin/user/userDescribe.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (42, '/admin/user/userRecovery.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (43, '/admin/user/userImport.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (43, '/admin/user/improtUser.ajax', '1');


delete from AUTH_ATTR_ACTION WHERE ATTRIBUTE_ID = 38;
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (38, '/admin/system/binningTypeDictFlag.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (38, '/admin/system/binningLevelDictFlag.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (38, '/admin/system/binningUrgentDictFlag.ajax', '1');

INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (44, '/admin/system/devanningTypeDictFlag.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (44, '/admin/system/devanningLevelDictFlag.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (44, '/admin/system/devanningUrgentDictFlag.ajax', '1');