INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (40, 'UserManageDel', 'UserManage', '删除', '#', 2, 5, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (41, 'UserManageDetail', 'UserManage', '查看详情', '#', 2, 6, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (42, 'UserManageRecovery', 'UserManage', '恢复', '#', 2, 7, null, null, null);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (43, 'UserManageImport', 'UserManage', '导入', '#', 2, 8, null, null, null);



update AUTH_ATTRIBUTE set TITLE = '封存' where ATTRIBUTE_ID = 38;
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX, CREATE_USER_ID, UPDATE_TIME, CREATE_TIME) VALUES (44, 'DictManageRecovery', 'DictManage', '解封', '#', 2, 5, null, null, null);