UPDATE AUTH_ATTR_ACTION SET ACTION_URL = '/admin/task/devanningTask.ajax' WHERE ATTRIBUTE_ID = 26;
delete from AUTH_ATTR_ACTION WHERE ATTRIBUTE_ID IN (54,55,56);
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (54, '/admin/workLog/workLogViewManage.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (54, '/admin/workLog/queryWorkLogViewList.ajax', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (55, '/admin/workLog/exportWorkLog.download', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (56, '/admin/workLog/workLogViewVisual.do', '1');
INSERT INTO AUTH_ATTR_ACTION (ATTRIBUTE_ID, ACTION_URL, VERIFY_RESOURCE) VALUES (56, '/admin/workLog/WorkLogViewVisualByWeek.ajax', '1');
