delete from AUTH_ATTRIBUTE WHERE ATTRIBUTE_CODE IN ('WorkLogView','WorkLogViewExport','workLogViewVisual');

INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (54, 'avoidLandingCache', 'WorkLogViewManage', '日志查看', '#', 1, 1);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (55, 'WorkLogViewExport', 'WorkLogViewManage', '日志导出', '#', 2, 2);
INSERT INTO AUTH_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_CODE, MENU_CODE, TITLE, OPERATION_URL, OPERATION_TYPE, IDX) VALUES (56, 'workLogViewVisual', 'WorkLogViewManage', '日志可视化', '#', 2, 3);
